/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./LimitOrderProtocol.types";
import * as _1 from "./LimitOrderProtocol.client";
import * as _2 from "./EscrowFactory.types";
import * as _3 from "./EscrowFactory.client";
import * as _4 from "./EscrowDst.types";
import * as _5 from "./EscrowDst.client";
import * as _6 from "./EscrowSrc.types";
import * as _7 from "./EscrowSrc.client";
export namespace contracts {
  export const LimitOrderProtocol = {
    ..._0,
    ..._1
  };
  export const EscrowFactory = {
    ..._2,
    ..._3
  };
  export const EscrowDst = {
    ..._4,
    ..._5
  };
  export const EscrowSrc = {
    ..._6,
    ..._7
  };
}