/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  hashlock: string;
  maker: Addr;
  order_hash: string;
  rescue_delay: number;
  taker: Addr;
  timelocks: Timelocks;
  token: Coin;
}
export interface Timelocks {
  dest_cancellation: number;
  dest_public_withdrawal: number;
  dest_withdrawal: number;
  src_cancellation: number;
  src_public_cancellation: number;
  src_public_withdrawal: number;
  src_withdrawal: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  pull_funds: PullFundsMsg;
} | {
  withdraw: WithdrawMsg;
} | {
  withdraw_to: WithdrawToMsg;
} | {
  public_withdraw: WithdrawMsg;
} | {
  cancel: [];
} | {
  public_cancel: [];
};
export interface PullFundsMsg {
  amount: Coin;
  from: Addr;
}
export interface WithdrawMsg {
  secret: string;
}
export interface WithdrawToMsg {
  secret: string;
  tagret: Addr;
}
export type QueryMsg = {
  order_details: {};
};
export interface GetOrderDetailsResponse {
  deployed_at: number;
  hashlock: string;
  maker: Addr;
  order_hash: string;
  rescue_delay: number;
  taker: Addr;
  timelocks: Timelocks;
  token: Coin;
}