/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  escrow_code_id: number;
}
export type ExecuteMsg = {
  fill_order: FillOrderMsg;
};
export type Addr = string;
export type Uint128 = string;
export interface FillOrderMsg {
  auction_params: AuctionParameters;
  immutables: Immutables;
  making_amount: Coin;
  taker_traits: TakerTraits;
  taking_amount: Coin;
}
export interface AuctionParameters {
  duration: number;
  gas_cost: GasCost;
  initial_rate_bump: number;
  points: PricePoint[];
  start_time: number;
}
export interface GasCost {
  gas_bump_estimate: number;
  gas_price_estimate: number;
}
export interface PricePoint {
  coefficient: number;
  delay: number;
}
export interface Immutables {
  hashlock: string;
  maker: Addr;
  order_hash: string;
  rescue_delay: number;
  taker: Addr;
  timelocks: Timelocks;
}
export interface Timelocks {
  dest_cancellation: number;
  dest_public_withdrawal: number;
  dest_withdrawal: number;
  src_cancellation: number;
  src_public_cancellation: number;
  src_public_withdrawal: number;
  src_withdrawal: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface TakerTraits {
  threshold_taking_price: Uint128;
}
export type QueryMsg = string;